import type { NextPage } from 'next'
import Head from 'next/head'
// import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Space Tourism</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <main className='container example text-white'>
      <h1>Design system</h1>

      <section id="colors">

      </section>
    </main>

    </div>
  )
}

export default Home
